heat_template_version: 2014-10-16

parameters:
  my_keypair:
    type: string
    constraints:
      - custom_constraint: nova.keypair
  my_flavor:
    type: string
    constraints:
      - custom_constraint: nova.flavor
  my_image:
    type: string
    constraints:
      - custom_constraint: glance.image
  my_image_size:
    type: number
    constraints:
      - range:
          min: 10
  my_public_network:
    type: string
    default: net04_ext
    constraints:
      - custom_constraint: neutron.network
  my_private_network:
    type: string
    constraints:
      - custom_constraint: neutron.network
  my_security_group:
    type: string
    default: default_sg
  my_init:
    type: string
    default: |
      #!/bin/bash
      date >> /tmp/date
    description: cannot find right custom_constraint for this resource

resources:
  system_volume:
    type: OS::Cinder::Volume
    properties:
      size: {get_param: my_image_size}
      image: {get_param: my_image}
  instance:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: my_flavor}
      networks:
        - network: {get_param: my_private_network}
      key_name: {get_param: my_keypair}
      block_device_mapping:
        - device_name: vda
          volume_id: {get_resource: system_volume}
      user_data_format: RAW
      user_data: {get_param: my_init}
      availability_zone: "nova"
      security_groups:
        - {get_param: my_security_group} 
  instance_ip_association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: floating_ip}
      server_id: {get_resource: instance}
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: {get_param: my_public_network}

outputs:
  instance_info:
    value: {get_attr: [instance, show]}
