heat_template_version: 2014-10-16

parameters:
  instance_number:
    type: number
    constraints:
      - range: {min: 1, max: 10}
  instance_keypair:
    type: string
    constraints:
      - custom_constraint: nova.keypair
  instance_flavor:
    type: string
    default: 1core2GBmemory20GBdisk
    description:
      - allowed_values:
        - 1core2GBmemory20GBdisk
        - 2cores4GBmemory40GBdisk
        - 4cores8GBmemory80GBdisk
        - 8cores16GBmemory160GBdisk
    constraints:
      - custom_constraint: nova.flavor
  instance_image:
    type: string
    default: Wordpress
    description:
      - allowed_values:
        - Wordpress
    constraints:
      - custom_constraint: glance.image
  instance_image_size:
    type: number
    constraints:
      - range:
          min: 10
  instance_public_network:
    type: string
    default: net04_ext
    constraints:
      - custom_constraint: neutron.network
  instance_private_network:
    type: string
    constraints:
      - custom_constraint: neutron.network
  matlab_license_ip:
    type: string
    default: 1.1.1.1
    description: dummy parameters in Wordpress solution
    constraints:
      - allowed_pattern: "([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])"
  portal_ip:
    type: string
    default: 1.1.1.1
    description: dummy parameters in Wordpress solution
    constraints:
      - allowed_pattern: "([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])"
  master_ip:
    type: string
    default: 1.1.1.1
    description: dummy parameters in Wordpress solution
    constraints:
      - allowed_pattern: "([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])"
  account_name:
    type: string
    default: 'Admin'
    description: account name for Windows OS
  account_pass:
    type: string
    default: 'password'
    description: account password for Windows OS
  instance_type:
    type: string
    default: Gemini::Server::BootFromVolume
    constraints:
      - allowed_values:
        - Gemini::Server::BootFromVolume
        - Gemini::Server::BootFromImage

resources:
  wordpress_cloud_config:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        output:
          all: '| tee -a /var/log/cloud-init-output.log'
  wordpress_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: wordpress_cloud_config}
  wordpress_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: instance_number}
      resource_def:
        type: {get_param: instance_type}
        properties:
          my_keypair: {get_param: instance_keypair}
          my_flavor: {get_param: instance_flavor}
          my_image: {get_param: instance_image}
          my_image_size: {get_param: instance_image_size}
          my_public_network: {get_param: instance_public_network}
          my_private_network: {get_param: instance_private_network}
          my_init: {get_resource: wordpress_init}

outputs:
  Detail:
    description: Stack Detail
    value:
      - name: Redirection
        icon: glyphicon-new-window
        value:
          - name: Website
            type: Button
            value: http://$public_ip[0]/wordpress
            description: This will open a redirect in a new window.
          - name: Console
            type: Button
            value: http://10.12.20.1:6080/vnc_auto.html?token=16223dae-b2f8-4edc-8a3f-f90f67434003
            description: This block is for console redirection.
  public_ip:
    description: This is public IP information.
    value: {get_attr: [wordpress_group, attributes, instance_public_ip]}
  stack_des:
    value:
      - name: wordpress_group_info
        type: OS:Heat:Resource
        role: Wordpress
        number: {get_param: instance_number}
  wordpress_group_info:
    description: Group Info
    value: {get_attr: [wordpress_group, attributes, instance_info]}
