heat_template_version: '2014-10-16'

parameters:
  instance_site_id:
    type: number
  instance_account:
    type: string
  instance_number:
    type: number
    constraints:
      - range: {min: 1, max: 10}
  instance_keypair:
    type: string
    constraints:
      - custom_constraint: nova.keypair
  instance_flavor:
    type: string
    description:
      - allowed_values:
        - 2cores4GBmemory50GBdisk
        - 4cores8GBmemory80GBdisk
    constraints:
      - custom_constraint: nova.flavor
  instance_image:
    type: string
    description:
      - allowed_values:
        - NxWitnessWin50G
    constraints:
      - custom_constraint: glance.image
  instance_image_size:
    type: number
    constraints:
      - range:
          min: 20
  instance_public_network:
    type: string
    constraints:
      - custom_constraint: neutron.network
  instance_private_network:
    type: string
    constraints:
      - custom_constraint: neutron.network
  instance_type:
    type: string
    constraints:
      - allowed_values:
        - Gemini::LinuxServer::BootFromVolume
        - Gemini::LinuxServer::BootFromImage
        - Gemini::WindowsServer::BootFromVolume
        - Gemini::WindowsServer::BootFromImage
  portal_ip:
    type: string
    constraints:
      - allowed_pattern: "([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])"

resources:
  instance_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name:
        str_replace:
          template: $site_id_$stack_name_sg
          params:
            $site_id: {get_param: instance_site_id}
            $stack_name: {get_param: 'OS::stack_name'}
      rules:
       - protocol: tcp
         port_range_max: 7001
         port_range_min: 7001
  nxwitness_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: instance_number}
      resource_def:
        type: {get_param: instance_type}
        properties:
          my_stack_name: {get_param: 'OS::stack_name'}
          my_site_id: {get_param: instance_site_id}
          my_index: '%index%'
          my_account: {get_param: instance_account}
          my_keypair: {get_param: instance_keypair}
          my_flavor: {get_param: instance_flavor}
          my_image: {get_param: instance_image}
          my_image_size: {get_param: instance_image_size}
          my_public_network: {get_param: instance_public_network}
          my_private_network: {get_param: instance_private_network}
          my_security_group: {get_resource: instance_security_group}
          portal_ip: {get_param: portal_ip}

outputs:
  stack_des:
    value:
      - name: nxwitness_group_info
        type: OS:Heat:Resource
        role: NxWitness
        number: {get_param: instance_number}
  nxwitness_group_info:
    description: Group Info
    value: {get_attr: [nxwitness_group, attributes, instance_info]}
